services:
  - type: web
    name: gmc-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npx prisma generate --schema=packages/database/prisma/schema.prisma && npx prisma db push --schema=packages/database/prisma/schema.prisma --accept-data-loss && npm run build --workspace=@gmc/api
    startCommand: node apps/api/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_3gBUqFN0XDMY@ep-plain-term-b3aqoho3-pooler.c-4.ap-southeast-1.aws.neon.tech/gmc?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: hn3ilyys
      - key: CLOUDINARY_API_KEY
        value: 556379479283928
      - key: CLOUDINARY_API_SECRET
        value: 9p769qWeAFhUx0UUChkYe_7traI
